name: riverpod_starter_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  dotenv: ^4.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_i18n: ^0.33.0
  flutter_riverpod: ^2.3.6
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/translations/
    - .env
